### ISSUE TITLE
Scalable?

### ISSUE THREAD

**Issue by cantino** [ncdc/openshift-foreman-cartridge#1]
I made a fork of this cartridge and am trying to get this to run with the `-s` scalable mode.  My fork switches it to `ruby200` and passes in `web=0` to the foreman process.  Otherwise, it's the same.  When I run with `-s`, I get

```
Creating application 'test' ... cantino-foreman-0.63.0 cannot be embedded in scalable app 'test'.
```

See: http://stackoverflow.com/questions/26090816/trying-to-run-foreman-on-openshift-having-cartridge-issues

Does anyone have any ideas?

**Comment by ncdc** [comment]
@cantino it looks like we need to modify the cartridge's categories. See http://openshift.github.io/documentation/oo_cartridge_developers_guide.html#categories for more details.  Because it currently only lists the embedded category, it doesn't know what to do in a scalable app. You might try setting the categories to embedded and plugin, and then set the group overrides to foreman and web_framework.

**Comment by cantino** [comment]
Thanks!  I'll give that a try.

**Comment by cantino** [comment]
I think that worked, thank you!

**Comment by pranny** [comment]
I tried installing this and got the same error

```
andygoldstein-foreman-0.63.0 cannot be embedded in scalable app 'loop'
```
